# User.create!(email: "ed@gmail.com", password: "kami3107", username: "itaru", introduce: "I am Itaru Tokuda web developer")
# User.create!(email: "papa@gmail.com", password: "kami3107", username: "papa", introduce: "I am Papa Tokuda")
# User.create!(email: "smith@gmail.com", password: "kami3107",  username: "smith", introduce: "I am Smith Smith web developer")
# User.create!(email: "mama@gmail.com", password: "kami3107",  username: "mama", introduce: "I am Mama Tokuda web developer")
# User.create!(email: "hana@gmail.com", password: "kami3107",  username: "hana", introduce: "I am Hana Tokuda web developer")
# User.create!(email: "brian@gmail.com", password: "kami3107",  username: "brian", introduce: "I am Brian Tokuda web developer")
# User.create!(email: "micheal@gmail.com", password: "kami3107",  username: "micheal", introduce: "I am micheal Tokuda web developer")
# User.create!(email: "stephan@gmail.com", password: "kami3107",  username: "stephan", introduce: "I am Stephan Tokuda web developer")
# User.create!(email: "chris@gmail.com", password: "kami3107",  username: "chris", introduce: "I am Chris Tokuda web developer")
# User.create!(email: "thai@gmail.com", password: "kami3107",  username: "thai", introduce: "I am Thai Tokuda web developer")
# User.create!(email: "ian@gmail.com", password: "kami3107",  username: "ian", introduce: "I am Ian Tokuda web developer")
# User.create!(email: "sam@gmail.com", password: "kami3107",  username: "sam", introduce: "I am Sam Tokuda web developer")
# User.create!(email: "tom@gmail.com", password: "kami3107",  username: "tom", introduce: "I am Tom web developer")
# User.create!(email: "edgmail.com", password: "kami3107", username: "itaru", introduce: "I am Itaru Tokuda web developer")
# User.create!(email: "pap@gmail.com", password: "kami3107", username: "papa", introduce: "I am Papa Tokuda")
# User.create!(email: "smit@gmail.com", password: "kami3107",  username: "smith", introduce: "I am Smith Smith web developer")
# User.create!(email: "mam@gmail.com", password: "kami3107",  username: "mama", introduce: "I am Mama Tokuda web developer")
# User.create!(email: "han@gmail.com", password: "kami3107",  username: "hana", introduce: "I am Hana Tokuda web developer")
# User.create!(email: "bria@gmail.com", password: "kami3107",  username: "brian", introduce: "I am Brian Tokuda web developer")
# User.create!(email: "michea@gmail.com", password: "kami3107",  username: "micheal", introduce: "I am micheal Tokuda web developer")
# User.create!(email: "stepha@gmail.com", password: "kami3107",  username: "stephan", introduce: "I am Stephan Tokuda web developer")
# User.create!(email: "chri@gmail.com", password: "kami3107",  username: "chris", introduce: "I am Chris Tokuda web developer")
# User.create!(email: "tha@gmail.com", password: "kami3107",  username: "thai", introduce: "I am Thai Tokuda web developer")
# User.create!(email: "ia@gmail.com", password: "kami3107",  username: "ian", introduce: "I am Ian Tokuda web developer")
# User.create!(email: "sa@gmail.com", password: "kami3107",  username: "sam", introduce: "I am Sam Tokuda web developer")
# User.create!(email: "to@gmail.com", password: "kami3107",  username: "tom", introduce: "I am Tom web developer")

# user = User.first
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user.id)
# Caffe.create!(name: "caffe nimman caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user.id)
# Caffe.create!(name: "caffe nimman caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user.id)

# user2 = User.find_by(id: 2)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user2.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user2.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user2.id)

# user3 = User.find_by(id: 3)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user3.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user3.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user3.id)

# user4 = User.find_by(id: 4)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user4.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user4.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user4.id)

# user5 = User.find_by(id: 5)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user5.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user5.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user5.id)

# user6 = User.find_by(id: 6)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user6.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user6.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user6.id)

# user7 = User.find_by(id: 7)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user7.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user7.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user7.id)

# user8 = User.find_by(id: 8)
# Caffe.create!(name: "caffe nimman", comment: "awesome caffe in Chiang mai", user_id: user8.id)
# Caffe.create!(name: "caffe nimman", comment: "Perfect place for Digital Nomad", user_id: user8.id)
# Caffe.create!(name: "caffe nimman", comment: "Fantastic place for Digital Nomad", user_id: user8.id)
# puts "初期データの投入に成功しました！"
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
